In [1]:
import numpy as np

In [4]:
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [6]:
vazio = np.empty([3,2],dtype= int)
print(vazio)

[[-1480475408         371]
 [          0           0]
 [        112           0]]


In [8]:
ones = np.ones([4,5], dtype= str)
print(ones)

[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


In [9]:
identidade = np.eye(4)
print(identidade)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
num = input("insira um num de 1 a 10")
num = int(num)

while num < 10:
    num = num + 1
    print(num)

4
5
6
7
8
9
10
